export default [
  "Health",
  "HP",
  "HP Recovery",
  "HP Recovery per Kill",
  "P. Atk",
  "P. Def",
  "M. Atk",
  "M. Def",
  "Ele. Atk",
  "Ele. Def",
  "Spirit Atk",
  "Increase STR",
  "Increase AGI",
  "Increase INT",
  "Cr. Rate",
  "Cr. Dmg",
  "Skill CD",
  "Atk Delay",
  "Movementspeed",
  "Inventoryslots"
];
