export default [
  "Health",
  "P. Atk",
  "P. Def",
  "M. Atk",
  "M. Def",
  "Ele. Atk",
  "Ele. Def",
  "Spirit Atk",
  "Increase STR",
  "Increase AGI",
  "Increase INT",
  "Cr. Rate",
  "Cr. Dmg",
  "Skill CD",
  "Atk Delay",
  "HP Recovery per Kill",
  "HP Recovery",
  "Movementspeed"
];
